// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddPlayerReducer from "../add_player_reducer";
import AddPointsReducer from "../add_points_reducer";
import RemovePlayerReducer from "../remove_player_reducer";
import SubtractPointsReducer from "../subtract_points_reducer";

export type AddPlayerParams = __Infer<typeof AddPlayerReducer>;
export type AddPointsParams = __Infer<typeof AddPointsReducer>;
export type RemovePlayerParams = __Infer<typeof RemovePlayerReducer>;
export type SubtractPointsParams = __Infer<typeof SubtractPointsReducer>;

